<?php

namespace AppBundle\Repository;

/**
 * AccessRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
