<?php

namespace AppBundle\Repository;

/**
 * AccompagnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccompagnementRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($agence)
    {
        $em = $this->getEntityManager();
        
        $query = "  select a.id, a.nom, a.description, a.prix
                    from accompagnement a
                    where a.nom is not null ";

        if ($agence) {
            $query .= " and a.agence = " . $agence ;
        }

        $query .= " order by a.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
