<?php

namespace AppBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getList()
	{
		$em = $this->getEntityManager();
		
		$query = "	select a.nom, a.region, a.code, a.capacite, '' as action , a.id as id
					from agence a
					order by a.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}

}
