<?php

namespace AppBundle\Repository;

/**
 * AnnulationNuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnulationNuitRepository extends \Doctrine\ORM\EntityRepository
{
}
