<?php

namespace AppBundle\Repository;

/**
 * AutorisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorisationRepository extends \Doctrine\ORM\EntityRepository
{
}
