<?php

namespace AppBundle\Repository;

/**
 * BanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanqueRepository extends \Doctrine\ORM\EntityRepository
{
	public function list($agence)
	{

		$em = $this->getEntityManager();
		
		$query = "	select b.*
					from banque b
					inner join agence ag on (b.agence = ag.id)";

		if ($agence) {
			$query .= "	where ag.id = " . $agence;
		}

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}
}
