<?php

namespace AppBundle\Repository;

/**
 * BonLivraisonDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonLivraisonDetailsRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation($bon_livraison)
    {
        $em = $this->getEntityManager();

        $query = "  select d.*, pr.nom as produit, pr.id as produit_id, s.nom as service, s.id as service_id, pr.unite
                    from bon_livraison_details d
                    left join variation_produit vp on (d.variation_produit = vp.id)
                    left join produit_entrepot pe on (vp.produit_entrepot = pe.id)
                    left join entrepot e on (pe.entrepot = e.id)
                    left join produit pr on (pe.produit = pr.id)
                    left join service s on (d.service = s.id)
                    where d.id is not null ";
        
        if ($bon_livraison) {
            $query .= " and d.bon_livraison = " . $bon_livraison ;
        }

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
