<?php

namespace AppBundle\Repository;

/**
 * BonLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation(
        $agence, 
        $id = 0,
        $type_date = '', 
        $mois = '', 
        $annee = '', 
        $date_specifique = '', 
        $debut_date = '', 
        $fin_date = ''
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select b.id, date_format(b.date, '%d/%m/%Y') as date, LPAD(b.id, 6, '0') as num, IF(c.statut = 1,cm.nom_societe,cp.nom) as client, b.statut
                    from bon_livraison b
                    left join client c on (b.client = c.num_police)
                    left join client_morale cm on (c.id_client_morale=cm.id)
                    left join client_physique cp on (c.id_client_physique=cp.id)
                    where b.id is not null ";

        if ($agence) {
            $query .= " and b.agence = " . $agence ;
        }

        if ($id) {
            $query .= " and b.id = " . $id ;
        }

        if ($type_date) {
            switch ($type_date) {
                case '1':
                    $now = new \DateTime();
                    $dateNow = $now->format('d-m-Y');
                    $query .= " and date_format(b.date,'%d-%m-%Y') = '" . $dateNow ."'";
                    break;
                
                case '2':
                    $moisAnnee = $mois . "-" . $annee;
                    $query .= " and date_format(b.date,'%m-%Y') = '" . $moisAnnee ."'";
                    break;

                case '3':
                    $query .= " and date_format(b.date,'%Y') = '" . $annee ."'";
                    break;

                case '4':
                    // $date = \DateTime::createFromFormat('j/m/Y', $date_specifique);
                    $query .= " and date_format(b.date,'%d/%m/%Y') = '" . $date_specifique ."'";
                    break;

                case '5':
                    $query .= " and date_format(b.date,'%d/%m/%Y') >= '" . $debut_date ."'";
                    $query .= " and date_format(b.date,'%d/%m/%Y') <= '" . $fin_date ."'";
                    break;
            }
        }

        $query .= " and b.is_delete IS NULL"; 

        $query .= " order by b.id desc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function consultationCorbeille(
        $agence, 
        $id = 0,
        $type_date = '', 
        $mois = '', 
        $annee = '', 
        $date_specifique = '', 
        $debut_date = '', 
        $fin_date = ''
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select b.id, date_format(b.date, '%d/%m/%Y') as date, LPAD(b.id, 6, '0') as num, IF(c.statut = 1,cm.nom_societe,cp.nom) as client, b.statut
                    from bon_livraison b
                    left join client c on (b.client = c.num_police)
                    left join client_morale cm on (c.id_client_morale=cm.id)
                    left join client_physique cp on (c.id_client_physique=cp.id)
                    where b.id is not null ";

        if ($agence) {
            $query .= " and b.agence = " . $agence ;
        }

        if ($id) {
            $query .= " and b.id = " . $id ;
        }

        if ($type_date) {
            switch ($type_date) {
                case '1':
                    $now = new \DateTime();
                    $dateNow = $now->format('d-m-Y');
                    $query .= " and date_format(b.date,'%d-%m-%Y') = '" . $dateNow ."'";
                    break;
                
                case '2':
                    $moisAnnee = $mois . "-" . $annee;
                    $query .= " and date_format(b.date,'%m-%Y') = '" . $moisAnnee ."'";
                    break;

                case '3':
                    $query .= " and date_format(b.date,'%Y') = '" . $annee ."'";
                    break;

                case '4':
                    // $date = \DateTime::createFromFormat('j/m/Y', $date_specifique);
                    $query .= " and date_format(b.date,'%d/%m/%Y') = '" . $date_specifique ."'";
                    break;

                case '5':
                    $query .= " and date_format(b.date,'%d/%m/%Y') >= '" . $debut_date ."'";
                    $query .= " and date_format(b.date,'%d/%m/%Y') <= '" . $fin_date ."'";
                    break;
            }
        }

        $query .= " and b.is_delete = 1"; 

        $query .= " order by b.id desc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
