<?php

namespace AppBundle\Repository;

/**
 * BureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureauRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($cle)
    {
        $em = $this->getEntityManager();
        
        $query = "  select b.id, b.nom, b.adresse, b.tel, b.email, b.img
                    from bureau b
                    inner join siteweb si on (b.siteweb = si.id)
                    where b.id is not null ";

        $query .= " and si.cle = '" . $cle  . "'";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function details($id)
    {
        $em = $this->getEntityManager();
        
        $query = "  select b.id, b.nom, b.adresse, b.tel, b.email, b.img
                    from bureau b
                    inner join siteweb si on (b.siteweb = si.id)
                    where b.id is not null ";

        $query .= " and b.id = " . $id ;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            return $result[0];
        }

        return [];
    }
}
