<?php

namespace AppBundle\Repository;

/**
 * ConditionHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
