<?php

namespace AppBundle\Repository;

/**
 * CreditDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditDetailsRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation($credit)
    {
        $em = $this->getEntityManager();

        $query = "  select cd.*, pr.nom as produit, pr.id as produit_id, s.nom as service, s.id as service_id, pr.unite
                    from credit_details cd
                    left join variation_produit vp on (cd.variation_produit = vp.id)
                    left join produit_entrepot pe on (vp.produit_entrepot = pe.id)
                    left join entrepot e on (pe.entrepot = e.id)
                    left join produit pr on (pe.produit = pr.id)
                    left join service s on (cd.service = s.id)
                    where cd.id is not null ";
        
        if ($credit) {
            $query .= " and cd.credit = " . $credit ;
        }

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
