<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($cle)
    {
        $em = $this->getEntityManager();
        
        $query = "  select c.id, c.nom, c.img, c.desactive
                    from customer c
                    inner join siteweb si on (c.siteweb = si.id)
                    where c.id is not null ";

        $query .= " and si.cle = '" . $cle  . "'";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function details($id)
    {
        $em = $this->getEntityManager();
        
        $query = "  select c.id, c.nom, c.img
                    from customer c
                    inner join siteweb si on (c.siteweb = si.id)
                    where c.id is not null ";

        $query .= " and c.id = " . $id ;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            return $result[0];
        }

        return [];
    }
}
