<?php

namespace AppBundle\Repository;

/**
 * DesignationDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesignationDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
