<?php

namespace AppBundle\Repository;

/**
 * DetailsDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
