<?php

namespace AppBundle\Repository;

/**
 * DevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($cle)
    {
        $em = $this->getEntityManager();
        
        $query = "  select d.*
                    from devis d
                    inner join siteweb si on (d.siteweb = si.id)
                    where d.id is not null ";

        $query .= " and si.cle = '" . $cle . "'";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
