<?php

namespace AppBundle\Repository;

/**
 * EmporterDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmporterDetailsRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation($emporter, $type = 0)
    {
        $em = $this->getEntityManager();

        $query = "  select ed.id, p.nom as plat, ed.qte, ed.prix, ed.total, ed.statut, ed.accompagnements, p.id as plat_id, p.type, ed.cuisson
                    from emporter_details ed
                    inner join plat p on (ed.plat = p.id)
                    where ed.id is not null ";
        
        if ($emporter) {
            $query .= " and ed.emporter = " . $emporter ;
        }

        if ($type) {
            if ($type == 1) {
                $query .= " and p.type != 2";
            } else {
                $query .= " and p.type = 2"; 
            }
        }

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        foreach ($result as $key => $value) {
            $accompagnementsDetails = $this->accompagnementsDetails($value['accompagnements']);
            $result[$key]['accompagnements'] = $accompagnementsDetails['accompagnements'];
            $result[$key]['total_accompagnement'] = $accompagnementsDetails['total_accompagnement'];
        }

        return $result;
    }


    public function accompagnementsDetails($accompagnements)
    {

        $data = [];

        $accompagnements = json_decode($accompagnements, true);

        if (is_array($accompagnements)) {
            $accompagnement_list = array_key_exists('accompagnement', $accompagnements) ? $accompagnements['accompagnement'] : [];
            $qte_accompagnement_list = array_key_exists('qte_accompagnement', $accompagnements) ? $accompagnements['qte_accompagnement'] : [];
            $prix_accompagnement_list = array_key_exists('prix_accompagnement', $accompagnements) ? $accompagnements['prix_accompagnement'] : [];
            $total_accompagnement = array_key_exists('total_accompagnement', $accompagnements) ? $accompagnements['total_accompagnement'] : '0.00';

            foreach ($accompagnement_list as $key => $value) {
                $item = array(
                    'accompagnement' => $accompagnement_list[$key],
                    'qte_accompagnement' => $qte_accompagnement_list[$key],
                    'prix_accompagnement' => $prix_accompagnement_list[$key],
                );

                array_push($data, $item);
            }

            return array(
                'accompagnements' => $data,
                'total_accompagnement' => $total_accompagnement,
            );
        }

        return array(
            'accompagnements' => $data,
            'total_accompagnement' => 0,
        );


    }
}
