<?php

namespace AppBundle\Repository;

/**
 * EntreeSortieStockInterneGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeSortieStockInterneGeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
