<?php

namespace AppBundle\Repository;

/**
 * EntreeSortieStockInterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeSortieStockInterneRepository extends \Doctrine\ORM\EntityRepository
{
}
