<?php

namespace AppBundle\Repository;

/**
 * FactureProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFactureProduit($id)
    {
        $sql = "SELECT p.*, vp.stock, fp.commande, pe.indice, vp.id as vpId, fpd.* FROM `facture_produit_details` fpd 
                JOIN facture_produit fp ON fp.id = fpd.facture_produit
                LEFT JOIN variation_produit vp ON fpd.variation_produit = vp.id
                JOIN produit_entrepot pe ON pe.id = vp.produit_entrepot 
                JOIN produit p ON p.id = pe.produit 
                WHERE fp.id = ? ";

        $em = $this->getEntityManager();
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($id));
        $result = $statement->fetchAll();

        return $result;
    }
}
