<?php

namespace AppBundle\Repository;

/**
 * FactureHebergementDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureHebergementDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
