<?php

namespace AppBundle\Repository;

/**
 * FactureHebergementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureHebergementRepository extends \Doctrine\ORM\EntityRepository
{
}
