<?php

namespace AppBundle\Repository;

/**
 * FactureServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureServiceRepository extends \Doctrine\ORM\EntityRepository
{
    
}
