<?php

namespace AppBundle\Repository;

/**
 * FactureRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
