<?php

namespace AppBundle\Repository;

/**
 * FactureProduitServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureProduitServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
