<?php

namespace AppBundle\Repository;

/**
 * FormulaireClientDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireClientDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
