<?php

namespace AppBundle\Repository;

/**
 * FormulaireClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireClientRepository extends \Doctrine\ORM\EntityRepository
{
}
