<?php

namespace AppBundle\Repository;

/**
 * FormulaireDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
