<?php

namespace AppBundle\Repository;

/**
 * HistoTypeTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoTypeTacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function verifieHistoTypeTache($idTypeTache,$idTache)
    {
        $em = $this->getEntityManager(); // GESTIONNAIRE D'ENTITE
        $sql = "SELECT * FROM `histo_type_tache` WHERE `idtypetache` = ? AND `idtache` = ?";
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($idTypeTache,$idTache));
        $result = $statement->fetch();
        return $result ; 
    }

    public function affaceHistoTypeTahce($idTypeTache,$idTache)
    {
        $em = $this->getEntityManager(); // GESTIONNAIRE D'ENTITE
        $sql = "DELETE FROM `histo_type_tache` WHERE `idtypetache` = ? AND `idtache` = ?";
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($idTypeTache,$idTache));
        // $result = $statement->fetch();
        // return $result ; 
    }
}
