<?php

namespace AppBundle\Repository;

/**
 * LibelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibelleRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($agence)
    {
        $em = $this->getEntityManager();
        
        $query = "  select l.*
                    from libelle l
                    where l.nom is not null ";

        if ($agence) {
            $query .= " and l.agence = " . $agence ;
        }

        $query .= " order by l.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
