<?php

namespace AppBundle\Repository;

/**
 * ModePayementDepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModePayementDepenseRepository extends \Doctrine\ORM\EntityRepository
{
}
