<?php

namespace AppBundle\Repository;

/**
 * PaiementCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementCreditRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSommePayee($idc)
    {
        $em = $this->getEntityManager();
        $sql ="SELECT SUM(`montant`) as m_payee FROM `paiement_credit` WHERE `credit` = ? " ;
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute([$idc]);
        $result = $statement->fetch();
        return $result ; 
    }
}
