<?php

namespace AppBundle\Repository;

/**
 * PannierBonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PannierBonRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation($bon_commande)
    {
        $em = $this->getEntityManager();

        $query = "  select pb.*, pr.nom as produit, pr.id as produit_id, s.nom as service, s.id as service_id, pr.unite
                    from pannier_bon pb
                    left join variation_produit vp on (pb.variation_produit = vp.id)
                    left join produit_entrepot pe on (vp.produit_entrepot = pe.id)
                    left join entrepot e on (pe.entrepot = e.id)
                    left join produit pr on (pe.produit = pr.id)
                    left join service s on (pb.service = s.id)
                    where pb.id is not null ";
        
        if ($bon_commande) {
            $query .= " and pb.bon_commande = " . $bon_commande ;
        }

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
