<?php

namespace AppBundle\Repository;

/**
 * PdfAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfAgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
