<?php

namespace AppBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(
        $agence, 
        $recherche_par = '', 
        $a_rechercher = '',
        $categorie = 0
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select p.id, p.nom, p.prix, p.prix_vente, p.statut, c.nom as categorie, p.type
                    from plat p
                    left join categorie_plat c on (p.categorie_plat = c.id)
                    where p.nom is not null ";

        if ($agence) {
            $query .= " and p.agence = " . $agence ;
        }

        if ($recherche_par == 1) {
            $query .= " and p.nom like '%" . $a_rechercher . "%'";
        }

        $query .= " order by c.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
