<?php

namespace AppBundle\Repository;


/**
 * PreferenceCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceCategorieRepository extends \Doctrine\ORM\EntityRepository
{
    
}
