<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

	public function nonAffecteEntrepot($agence)
	{
		$em = $this->getEntityManager();

		// $query = "	select p.id, pe.id as produit_entrepot
		// 			from produit p
		// 			left join produit_entrepot pe on (pe.produit = p.id)
		// 			left join entrepot e on (pe.entrepot = e.id)
		// 			where p.id is not null";

		$query = "	select p.id, pe.id as produit_entrepot
					from produit p
					left join produit_entrepot pe on (pe.produit = p.id)
					left join entrepot e on (pe.entrepot = e.id)
					where (pe.id is null
					or e.id is null)";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		$statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}

	public function getList(
		$agence, 
		$recherche_par = '', 
		$a_rechercher = '',
		$categorie = 0,
		$produit_id = 0
	)
	{
		$em = $this->getEntityManager();

		$query =
		"	select p.code_produit, p.id, p.nom, pe.stock, cp.nom as categorie, pe.indice
					from produit p
					left join categorie_produit cp on (p.categorie_produit = cp.id)
					left join produit_entrepot pe on (pe.produit = p.id)
					left join variation_produit vp on vp.produit_entrepot = pe.id
					where p.nom is not null and vp.is_delete is null";
		
		// $query = "	SELECT DISTINCT p.*,cp.*, cp.nom as categorie FROM `produit` p JOIN produit_entrepot pe ON pe.produit = p.id JOIN variation_produit ON variation_produit.produit_entrepot = pe.id JOIN categorie_produit cp ON cp.id = p.categorie_produit WHERE variation_produit.is_delete IS NULL AND p.nom IS NOT NULL";

		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		if ($recherche_par == 0) { 
			$query .= "	and p.code_produit like '%".$a_rechercher."%'";
		}

		if ($recherche_par == 1) {
			$query .= "	and p.nom like '%" . $a_rechercher . "%'";
		}

		if ($categorie) {
			$query .= "	and cp.id = " . $categorie;
		}

		if ($produit_id) {
			$query .= "	and p.id = " . $produit_id;
		}

		$query .= "	and p.is_delete IS NULL";

		$query .= "	group by p.code_produit ";

		$query .= "	order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}

	public function notifications(
		$agence, 
		$entrepot = 0
	)
	{
		$em = $this->getEntityManager();

		$query = "SELECT * FROM `variation_produit` v 
				JOIN produit_entrepot pe ON pe.id = v.produit_entrepot 
				LEFT JOIN produit p ON p.id = pe.produit 
				WHERE v.stock <= pe.stock_alerte AND p.is_delete IS NULL AND v.is_delete IS NULL ";
		if ($agence) {
			$query .= "	and p.agence = " . $agence ;
		}

		$query .= " GROUP BY v.id order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}

	public function getProduitInEntrepot($idAgence)
	{
		$em = $this->getEntityManager();
		$sql = "SELECT produit.* FROM `produit` JOIN produit_entrepot ON produit_entrepot.produit = produit.id WHERE produit.agence = ? " ;
		$statement = $em->getConnection()->prepare($sql);
		$statement->execute(array($idAgence));
		$result = $statement->fetchAll();
		return $result;
	}

	public function getAllProduit($idAgence)
	{
		$em = $this->getEntityManager();
		$sql = "SELECT * FROM `produit` WHERE `agence` = ? AND `is_delete` IS NULL GROUP BY code_produit  ORDER BY code_produit ASC " ;
		$statement = $em->getConnection()->prepare($sql);
		$statement->execute(array($idAgence));
		$result = $statement->fetchAll();
		return $result;
	}
}
