<?php

namespace AppBundle\Repository;

/**
 * ProduitEntrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitEntrepotRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(
        $agence, 
        $entrepot = 0, 
        $recherche_par = '', 
        $a_rechercher = '',
        $categorie = 0,
        $produit_id = 0
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select pe.id, p.code_produit, pe.indice, p.nom, pe.stock, cp.nom as categorie, e.nom as entrepot
                    from produit p
                    inner join produit_entrepot pe on (pe.produit = p.id)
                    inner join entrepot e on (pe.entrepot = e.id)
                    left join categorie_produit cp on (p.categorie_produit = cp.id)
                    where p.nom is not null ";

        if ($agence) {
            $query .= " and p.agence = " . $agence ;
        }

        if ($entrepot) {
            $query .= " and pe.entrepot = " . $entrepot ;
        }

        if ($recherche_par == 0) {
            $query .= " and p.code_produit like '%" . $a_rechercher . "%'";
        }

        if ($recherche_par == 1) {
            $query .= " and p.nom like '%" . $a_rechercher . "%'";
        }

        if ($categorie) {
            $query .= " and cp.id = " . $categorie;
        }

        if ($produit_id) {
            $query .= " and p.id = " . $produit_id;
        }

        $query .= " and p.is_delete IS NULL";

        $query .= " order by p.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function getProduitEntrepot($id)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT * FROM `produit_entrepot` WHERE `id` = ? " ;
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute([$id]);
        $result = $statement->fetch();
        return $result;
    }

    public function getProduitParEntrepot($entrepot)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT p.nom, p.code_produit, p.id FROM produit_entrepot pe 
                                JOIN produit p ON p.id = pe.produit 
                                JOIN variation_produit vp on vp.produit_entrepot = pe.id
                                AND pe.entrepot = ?
                                AND p.is_delete IS NULL
                                AND vp.is_delete IS NULL
                                GROUP BY p.code_produit
                                ORDER BY p.code_produit ASC";
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($entrepot));
        $result = $statement->fetchAll();
        return $result;
    }

    public function getRefProduitEntrepot($idProduit, $entrepot)
    {
        $em = $this->getEntityManager();
        $sql = "SELECT * FROM `produit_entrepot` WHERE `produit` = ? AND `entrepot` = ? " ;
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($idProduit,$entrepot));
        $result = $statement->fetchAll();
        return $result;
    }
}
