<?php

namespace AppBundle\Repository;

/**
 * RavitaillementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RavitaillementRepository extends \Doctrine\ORM\EntityRepository
{
	public function consultation(
		$agence,
		$type_date = '', 
        $mois = '', 
        $annee = '', 
        $date_specifique = '', 
        $debut_date = '', 
        $fin_date = ''
	)
	{
		$em = $this->getEntityManager();
		
		$query = "	select r.id, date_format(r.date, '%d/%m/%Y') as date, r.total as montant_total
					from ravitaillement r
					where r.id is not null ";

		if ($agence) {
			$query .= "	and r.agence = " . $agence ;
		}

		if ($type_date) {
            switch ($type_date) {
                case '1':
                    $now = new \DateTime();
                    $dateNow = $now->format('d-m-Y');
                    $query .= " and date_format(r.date,'%d-%m-%Y') = '" . $dateNow ."'";
                    break;
                
                case '2':
                    $moisAnnee = $mois . "-" . $annee;
                    $query .= " and date_format(r.date,'%m-%Y') = '" . $moisAnnee ."'";
                    break;

                case '3':
                    $query .= " and date_format(r.date,'%Y') = '" . $annee ."'";
                    break;

                case '4':
                    // $date = \DateTime::createFromFormat('j/m/Y', $date_specifique);
                    $query .= " and date_format(r.date,'%d/%m/%Y') = '" . $date_specifique ."'";
                    break;

                case '5':
                    $query .= " and date_format(r.date,'%d/%m/%Y') >= '" . $debut_date ."'";
                    $query .= " and date_format(r.date,'%d/%m/%Y') <= '" . $fin_date ."'";
                    break;
            }
        }

		$query .= "	order by r.id desc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}
}
