<?php

namespace AppBundle\Repository;

/**
 * RemboursementBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemboursementBookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($agence)
    {
        $em = $this->getEntityManager();

        $query = "  select rb.montant
                    from booking b
                    inner join remboursement_booking rb on (b.remboursement_booking = rb.id)";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

    }
}
