<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function consultation(
        $agence, 
        $statut = 100,
        $id = 0,
        $ficheconsommation = 0,
        $booking_id = 0,
        $type_date = '', 
        $mois = '', 
        $annee = '', 
        $date_specifique = '', 
        $debut_date = '', 
        $fin_date = ''
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select r.id, date_format(r.date,'%d/%m/%Y') as date, r.statut, r.total, CONCAT(LPAD(r.id, 6, '0'),'/SP') as num, r.selected_tables, r.nb_place, 'reservation' as type_commande, CONCAT(LPAD(b.id, 6, '0'),'/HB') as num_booking
                    from reservation r
                    left join booking b on (b.id = r.booking)
                    where r.id is not null ";

        if ($agence) {
            $query .= " and r.agence = " . $agence ;
        }

        if ($id) {
            $query .= " and r.id = " . $id ;
        }

        if ($booking_id) {
            $query .= " and b.id = " . $booking_id ;
        }

        if ($statut != 100) {
            if ($statut == 200) {
                $query .= " and r.statut > 1 " ;
            } else {
                if ($statut) {
                    $query .= " and r.statut = " . $statut ;
                }
            }
        }

        if ($ficheconsommation) {
            $query .= " and r.booking is not null";
        }

        if ($type_date) {
            switch ($type_date) {
                case '1':
                    $now = new \DateTime();
                    $dateNow = $now->format('d-m-Y');
                    $query .= " and date_format(r.date,'%d-%m-%Y') = '" . $dateNow ."'";
                    break;
                
                case '2':
                    $moisAnnee = $mois . "-" . $annee;
                    $query .= " and date_format(r.date,'%m-%Y') = '" . $moisAnnee ."'";
                    break;

                case '3':
                    $query .= " and date_format(r.date,'%Y') = '" . $annee ."'";
                    break;

                case '4':
                    // $date = \DateTime::createFromFormat('j/m/Y', $date_specifique);
                    $query .= " and date_format(r.date,'%d/%m/%Y') = '" . $date_specifique ."'";
                    break;

                case '5':
                    $query .= " and date_format(r.date,'%d/%m/%Y') >= '" . $debut_date ."'";
                    $query .= " and date_format(r.date,'%d/%m/%Y') <= '" . $fin_date ."'";
                    break;
            }
        }

        $query .= " order by r.id desc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            $response = [];

            foreach ($result as $value) {
                $tables = json_decode($value['selected_tables']);
                $item = $value;
                $item['tables'] = array();
                foreach ($tables as $t) {
                    $q = "  select *
                            from table_restaurant t
                            where t.id = " . $t->id;

                    $s = $em->getConnection()->prepare($q);
                    $s->execute();
                    $r = $s->fetchAll();

                    if (!empty($r)) {
                        $table = $r[0];
                        $table['assis'] = $t->assis;
                        array_push($item['tables'], $table);
                    }
                    

                }

                array_push($response, $item);
            }

            return $response;
        }

        return [];
    }

    public function notificationsReservations()
    {
        $compteur = 0;
        $em = $this->getEntityManager();
        $query = "select COUNT(res.id) as compteur from reservation res WHERE res.statut = 1";

        $statement = $em->getConnection()->prepare($query);
        $statement->execute();

        $result = $statement->fetchAll(); 

        return ($result[0]['compteur']) ? $result[0]['compteur'] : 0 ;
    }
}
