<?php

namespace AppBundle\Repository;

/**
 * SectionValeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionValeurRepository extends \Doctrine\ORM\EntityRepository
{
}
