<?php

namespace AppBundle\Repository;

/**
 * SitewebProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitewebProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($cle)
    {
        $em = $this->getEntityManager();
        
        $query = "  select sp.id, sp.nom, sp.description, sp.img, sp.icon
                    from siteweb_produit sp
                    inner join siteweb si on (sp.siteweb = si.id)
                    where sp.id is not null ";

        $query .= " and si.cle = '" . $cle  . "'";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function details($id)
    {
        $em = $this->getEntityManager();
        
        $query = "  select sp.id, sp.nom, sp.description, sp.img, sp.icon
                    from siteweb_produit sp
                    inner join siteweb si on (sp.siteweb = si.id)
                    where sp.id is not null ";

        $query .= " and sp.id = " . $id ;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            return $result[0];
        }

        return [];
    }
}
