<?php

namespace AppBundle\Repository;

/**
 * SitewebAproposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitewebAproposRepository extends \Doctrine\ORM\EntityRepository
{
    public function apropos($cle)
    {
        $em = $this->getEntityManager();

        $query = "  select sa.id, sa.slogon, sa.apropos, sa.titre, sa.adresse, sa.tel_fixe, sa.tel_mobile, sa.email, sa.facebook, sa.logo
                    from siteweb_apropos sa
                    inner join siteweb si on (sa.siteweb = si.id)
                    where si.nom is not null ";

        $query .= " and si.cle = '" . $cle . "'";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            return $result[0];
        }

        return [];

    }
}
