<?php

namespace AppBundle\Repository;

/**
 * SliderRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($agence)
    {
        $em = $this->getEntityManager();
        
        $query = "  select sl.id, sl.titre, sl.sous_titre, sl.img
                    from slider_restaurant sl
                    inner join agence a on (sl.agence = a.id)
                    where sl.id is not null ";

        $query .= " and sl.agence = " . $agence;

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
