<?php

namespace AppBundle\Repository;

/**
 * TableRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList(
        $agence, 
        $recherche_par = '', 
        $a_rechercher = '',
        $categorie = 0
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select t.*
                    from table_restaurant t
                    where t.nom is not null ";

        if ($agence) {
            $query .= " and t.agence = " . $agence ;
        }

        if ($recherche_par == 1) {
            $query .= " and t.nom like '%" . $a_rechercher . "%'";
        }

        $query .= " order by t.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }

    public function placeDisponible(
        $agence, 
        $table = ''
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select SUM(t.disponible) as places
                    from table_restaurant t
                    where t.statut = 1
                    and t.disponibilite = 1";

        if ($agence) {
            $query .= " and t.agence = " . $agence ;
        }

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        if (!empty($result)) {
            return $result[0]['places'];
        }

        return 0;
    }

    public function tablesDisponible(
        $agence
    )
    {
        $em = $this->getEntityManager();
        
        $query = "  select t.*
                    from table_restaurant t where ";
        if ($agence) {
            $query .= " t.agence = " . $agence ;
        }

        // $query .= " order by t.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
