<?php

namespace AppBundle\Repository;

/**
 * TarifCategorieChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifCategorieChambreRepository extends \Doctrine\ORM\EntityRepository
{
}
