<?php

namespace AppBundle\Repository;

/**
 * TarifServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function list($service)
	{
		$em = $this->getEntityManager();
		
		$query = "	select * 
					from tarif_service t
					where t.service = " . $service;

		$statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
	}
}
