<?php

namespace AppBundle\Repository;

/**
 * TarifChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifChambreRepository extends \Doctrine\ORM\EntityRepository
{
}
