<?php

namespace AppBundle\Repository;

/**
 * TypeChambreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeChambreRepository extends \Doctrine\ORM\EntityRepository
{
    public function list($agence)
    {
        $em = $this->getEntityManager();
        
        $query = "  select t.id, t.nom
                    from type_chambre t
                    where t.nom is not null ";

        if ($agence) {
            $query .= " and t.agence = " . $agence ;
        }

        $query .= " order by t.nom asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;
    }
}
