<?php

namespace AppBundle\Repository;

/**
 * TypeTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTacheRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllTypeTache($agenceId)
    {
        $em = $this->getEntityManager(); // GESTIONNAIRE D'ENTITE
        $sql = "SELECT * FROM `type_tache` WHERE `id_agence` = ? ORDER BY `nom_type_tache` ASC" ; // PREPARATION DE LA REQUETE
        $statement = $em->getConnection()->prepare($sql);
        $statement->execute(array($agenceId));
        $result = $statement->fetchAll();
        return $result ; 
    }
}
