<?php

namespace AppBundle\Repository;

/**
 * TypeSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeSocialRepository extends \Doctrine\ORM\EntityRepository
{
	public function list()
	{

		$em = $this->getEntityManager();
		
		$query = "	select t.designation as designation, t.descr as descr, '' as action, t.id as id 
					from type_social t
					order by t.designation asc";

        $statement = $em->getConnection()->prepare($query);

        $statement->execute();

        $result = $statement->fetchAll();

        return $result;

	}
}
