<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Agence;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAgenceRepository extends \Doctrine\ORM\EntityRepository
{
	public function countUserByAgence(Agence $agence)
	{
		$userAgence = $this->createQueryBuilder('ua')
		            ->innerJoin('ua.agence', 'ag')
		            ->innerJoin('ua.user', 'user')
		            ->where('ag = :agence')
		            ->andWhere('user.enabled = 1')
		            ->setParameters(array(
		                'agence' => $agence,
		            ))
		            ->getQuery()
		            ->getResult();
		return $userAgence;
	}

	public function getAllUserAgence($agenceId)
	{
		$sql = "SELECT fou.* FROM `fos_user` fou JOIN user_agence ua ON ua.user = fou.id WHERE ua.agence = ? " ;
        $em = $this->getEntityManager();
        $statement = $em->getConnection()->prepare($sql) ; 
        $statement->execute(array($agenceId));
		$result = $statement->fetchAll();
        return $result ;
	}
}
