<?php

namespace AppBundle\Repository;

/**
 * UserEntrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEntrepotRepository extends \Doctrine\ORM\EntityRepository
{
}
