tache:
    resource: "@TacheBundle/Resources/config/routing.yml"
    prefix:   /

stock_interne_general:
    resource: "@StockInterneGeneralBundle/Resources/config/routing.yml"
    prefix:   /

stock_interne:
    resource: "@StockInterneBundle/Resources/config/routing.yml"
    prefix:   /

hebergement:
    resource: "@HebergementBundle/Resources/config/routing.yml"
    prefix:   /

restaurant:
    resource: "@RestaurantBundle/Resources/config/routing.yml"
    prefix:   /

recette:
    resource: "@RecetteBundle/Resources/config/routing.yml"
    prefix:   /

credit:
    resource: "@CreditBundle/Resources/config/routing.yml"
    prefix:   /

bon_livraison:
    resource: "@BonLivraisonBundle/Resources/config/routing.yml"
    prefix:   /

motif_decharge:
    resource: "@MotifDechargeBundle/Resources/config/routing.yml"
    prefix:   /

bon_commande:
    resource: "@BonCommandeBundle/Resources/config/routing.yml"
    prefix:   /

api_config:
    resource: "@ApiConfigBundle/Resources/config/routing.yml"
    prefix:   /

api_siteweb:
    resource: "@ApiSitewebBundle/Resources/config/routing.yml"
    prefix:   /

siteweb:
    resource: "@SitewebBundle/Resources/config/routing.yml"
    prefix:   /

commercial:
    resource: "@CommercialBundle/Resources/config/routing.yml"
    prefix:   /

comptabilite:
    resource: "@ComptabiliteBundle/Resources/config/routing.yml"
    prefix:   /

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

caisse:
    resource: "@CaisseBundle/Resources/config/routing.yml"
    prefix:   /

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /

pdf:
    resource: "@PdfBundle/Resources/config/routing.yml"
    prefix:   /

facture:
    resource: "@FactureBundle/Resources/config/routing.yml"
    prefix:   /

permission_user:
    resource: "@PermissionUserBundle/Resources/config/routing.yml"
    prefix:   /

permission:
    resource: "@PermissionBundle/Resources/config/routing.yml"
    prefix:   /

agence:
    resource: "@AgenceBundle/Resources/config/routing.yml"
    prefix:   /

parametre:
    resource: "@ParametreBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

menu:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"