# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.html2pdf:
    class:  AppBundle\Service\Html2PdfService
    arguments: [%public_directory%]

  app.printer_pos:
    class:  AppBundle\Service\PrinterPosService
    
  app.logs:
    class:  AppBundle\Service\LogsService
    arguments: ['@doctrine.orm.entity_manager']

  app.permission_user:
    class:  AppBundle\Service\PermissionUserService
    arguments: ['@doctrine.orm.entity_manager']

  app.check_menu:
    class:  AppBundle\Service\CheckMenuService
    arguments: ['@doctrine.orm.entity_manager']
    
  app.twig_extension:
          class: AppBundle\Twig\AppExtension
          public: false
          tags:
              - { name: twig.extension }
              
  authentication_handler:
      class: AppBundle\Handler\AuthenticationHandler
      calls:
          # - [ setContainer, [ @service_container ] ]
      arguments:
        - "@security.token_storage"
        - "@doctrine.orm.entity_manager"
        - "@service_container"

  #Access validation - Menu
  security.access_validation:
        class: AppBundle\EventListener\MenuAllowed
        arguments:
          - "@security.token_storage"
          - "@security.authorization_checker"
          - "@doctrine.orm.entity_manager"
          - "@service_container"
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }

