service_homepage:
    path:     /service/index
    defaults: { _controller: ServiceBundle:Default:index }

service_add:
    path:     /service/add
    defaults: { _controller: ServiceBundle:Default:add }

service_save:
    path:     /service/save
    defaults: { _controller: ServiceBundle:Default:save }
    options:
        expose: true
    methods: [POST]

service_consultation:
    path:     /service/consultation
    defaults: { _controller: ServiceBundle:Default:consultation }

service_list:
    path:     /service/list
    defaults: { _controller: ServiceBundle:Default:list }
    options:
        expose: true
    methods: [POST]

service_show:
    path:     /service/show/{id}
    defaults: { _controller: ServiceBundle:Default:show }
    options:
        expose: true
    methods: [GET]

service_save_prix:
    path:     /service/save-prix
    defaults: { _controller: ServiceBundle:Default:savePrix }
    options:
        expose: true
    methods: [POST]

service_delete_prix:
    path:     /service/delete-prix/{id}
    defaults: { _controller: ServiceBundle:Default:deletePrix }
    options:
        expose: true
    methods: [GET]

service_editor_prix:
    path:     /service/editor-prix/editor
    defaults: { _controller: ServiceBundle:Default:editorPrix }
    methods:  [POST]
    options:
        expose: true

service_list_prix:
    path:     /service/list-prix
    defaults: { _controller: ServiceBundle:Default:listPrix }
    options:
        expose: true
    methods: [POST]